"use client";

import React, { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/components/ui/use-toast";
import { Rabbit, Trash2 } from "lucide-react";
import { useAuth } from "@/lib/auth-context";
import * as utils from "@/lib/utils";
import axios from "axios";
import type { Rabbit as RabbitType } from "@/lib/types";

interface KitFormData {
    kit_number: string;
    birth_weight: string;
    gender: "male" | "female" | "";
    color: string;
    status: "alive" | "dead" | "";
    notes: string;
}

interface AddKitDialogProps {
    rabbit: RabbitType;
    doeId: string;
    buckId: string;
    doeName?: string;
    buckName?: string;
    onClose: () => void;
    onKitAdded: () => void;
}

const colors = [
    "White", "Black", "Brown", "Gray", "Chocolate brown", "Golden", "Silver", "Blue",
    "Rust colored", "Orange-red", "Ivory", "White with black points", "Black and white",
    "White with black spots", "Black and white spotted",
];

export default function AddKitDialog({ rabbit, doeId, buckId, doeName, buckName, onClose, onKitAdded }: AddKitDialogProps) {
    const { user } = useAuth();
    const { toast } = useToast();
    const [actualBirthDate, setActualBirthDate] = useState<string>(new Date().toISOString().split("T")[0]);
    const [kits, setKits] = useState<KitFormData[]>([]);
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [nextKitNumber, setNextKitNumber] = useState<number>(1);

    // Fetch existing kits to determine next kit_number
    useEffect(() => {
        if (!user?.farm_id) return;
        const fetchKits = async () => {
            try {
                const response = await axios.get(`${utils.apiUrl}/kits/${user.farm_id}`, {
                    headers: { Authorization: `Bearer ${localStorage.getItem("rabbit_farm_token")}` },
                });
                const existingKits = response.data.data || [];
                const maxNumber = existingKits.reduce((max: number, kit: any) => {
                    const num = parseInt(kit.kit_number.replace("RB-", ""));
                    return isNaN(num) ? max : Math.max(max, num);
                }, 0);
                setNextKitNumber(maxNumber + 1);
            } catch (error) {
                console.error("Error fetching kits:", error);
                toast({
                    variant: "destructive",
                    title: "Error",
                    description: "Failed to fetch existing kits.",
                });
            }
        };
        fetchKits();
    }, [user, toast]);

    // Add a new kit with autogenerated kit_number
    const addKit = () => {
        setKits((prev) => [
            ...prev,
            {
                kit_number: `RB-${nextKitNumber.toString().padStart(3, "0")}`,
                birth_weight: "",
                gender: "",
                color: "",
                status: "alive",
                notes: "",
            },
        ]);
        setNextKitNumber((prev) => prev + 1);
    };

    // Remove a kit by index
    const removeKit = (index: number) => {
        setKits((prev) => prev.filter((_, i) => i !== index));
    };

    // Update a kit's field
    const updateKit = (index: number, field: keyof KitFormData, value: string) => {
        setKits((prev) =>
            prev.map((kit, i) =>
                i === index ? { ...kit, [field]: value } : kit
            )
        );
    };

    const validateKits = (): boolean => {
        if (!actualBirthDate || isNaN(new Date(actualBirthDate).getTime())) {
            toast({
                variant: "destructive",
                title: "Invalid data",
                description: "A valid actual birth date is required.",
            });
            return false;
        }
        for (const kit of kits) {
            if (!kit.kit_number || !kit.birth_weight || !kit.status) {
                toast({
                    variant: "destructive",
                    title: "Invalid data",
                    description: "Kit number, birth weight, and status are required for all kits.",
                });
                return false;
            }
            const birthWeight = parseFloat(kit.birth_weight);
            if (isNaN(birthWeight) || birthWeight <= 0) {
                toast({
                    variant: "destructive",
                    title: "Invalid birth weight",
                    description: `Birth weight for kit ${kit.kit_number} must be a positive number.`,
                });
                return false;
            }
            if (kits.filter((k) => k.kit_number === kit.kit_number).length > 1) {
                toast({
                    variant: "destructive",
                    title: "Duplicate kit number",
                    description: `Kit number ${kit.kit_number} is duplicated.`,
                });
                return false;
            }
        }
        return true;
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!user?.farm_id || !doeId || !buckId || kits.length === 0) {
            toast({
                variant: "destructive",
                title: "Missing data",
                description: "At least one kit and parent information are required.",
            });
            return;
        }

        if (!validateKits()) return;

        setIsLoading(true);
        try {
            // Update rabbit with actual_birth_date, is_pregnant, total_litters, total_kits
            await axios.patch(
                `${utils.apiUrl}/rabbits/${user.farm_id}/${doeId}`,
                {
                    actual_birth_date: actualBirthDate,
                    is_pregnant: false,
                    total_litters: (rabbit.total_litters ?? 0) + 1,
                    total_kits: (rabbit.total_kits ?? 0) + kits.length,
                },
                { headers: { Authorization: `Bearer ${localStorage.getItem("rabbit_farm_token")}` } }
            );

            // Create kit records in bulk
            const kitData = kits.map((kit) => ({
                kit_number: kit.kit_number,
                birth_weight: parseFloat(kit.birth_weight),
                gender: kit.gender || null,
                color: kit.color || null,
                status: kit.status || null,
                parent_male_id: buckId,
                parent_female_id: doeId,
                notes: kit.notes || null,
                actual_birth_date: actualBirthDate,
                farm_id: user.farm_id,
            }));

            const response = await axios.post(
                `${utils.apiUrl}/breeds/kits/${user.farm_id}`,
                { kits: kitData },
                { headers: { Authorization: `Bearer ${localStorage.getItem("rabbit_farm_token")}` } }
            );

            if (response.data.success) {
                toast({
                    title: "Success",
                    description: `${kits.length} kit${kits.length !== 1 ? "s" : ""} added successfully.`,
                });
                onKitAdded();
                onClose();
            } else {
                throw new Error("Failed to create kit records");
            }
        } catch (error: any) {
            console.error("Error creating kits:", error);
            toast({
                variant: "destructive",
                title: "Error",
                description: error.response?.data?.message || "Failed to add kit records.",
            });
        } finally {
            setIsLoading(false);
        }
    };

    // Summary of kits
    const femaleCount = kits.filter((kit) => kit.gender === "female").length;
    const maleCount = kits.filter((kit) => kit.gender === "male").length;

    return (
        <Dialog open={true} onOpenChange={onClose}>
            <DialogContent
                className="sm:max-w-[650px] bg-white dark:bg-gray-800 bg-clip-padding backdrop-blur-sm border-gray-200 dark:border-gray-700 max-h-[80vh] overflow-y-auto"
            >
                <DialogHeader className="bg-gradient-to-r from-green-400 to-blue-500 dark:from-green-600 dark:to-blue-600 -m-6 p-6 rounded-t-lg border-b border-gray-200 dark:border-gray-600">
                    <DialogTitle className="flex items-center space-x-2 text-white">
                        <Rabbit className="h-5 w-5 text-green-200" />
                        <span>Add Kits for {rabbit.name}</span>
                    </DialogTitle>
                </DialogHeader>
                <form onSubmit={handleSubmit} className="space-y-4">
                    <div>
                        <Label htmlFor="actual_birth_date" className="text-gray-900 dark:text-gray-100">
                            Actual Birth Date
                        </Label>
                        <Input
                            id="actual_birth_date"
                            type="date"
                            value={actualBirthDate}
                            onChange={(e: React.ChangeEvent<HTMLInputElement>) => setActualBirthDate(e.target.value)}
                            className="mt-1 bg-white/50 dark:bg-gray-700/50 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-gray-100"
                            required
                        />
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                        <div>
                            <Label htmlFor="parent_male_id" className="text-gray-900 dark:text-gray-100">
                                Parent Male (Buck)
                            </Label>
                            <Input
                                id="parent_male_id"
                                type="text"
                                value={buckName || buckId || "Unknown"}
                                className="mt-1 bg-gray-100 dark:bg-gray-600 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-gray-100 opacity-75 cursor-not-allowed"
                                disabled
                            />
                        </div>
                        <div>
                            <Label htmlFor="parent_female_id" className="text-gray-900 dark:text-gray-100">
                                Parent Female (Doe)
                            </Label>
                            <Input
                                id="parent_female_id"
                                type="text"
                                value={doeName || doeId || "Unknown"}
                                className="mt-1 bg-gray-100 dark:bg-gray-600 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-gray-100 opacity-75 cursor-not-allowed"
                                disabled
                            />
                        </div>
                    </div>
                    <div className="space-y-2">
                        <div className="flex justify-between items-center">
                            <Label className="text-gray-900 dark:text-gray-100 font-medium">
                                Kits ({kits.length} total: {femaleCount} female{maleCount !== 1 ? "s" : ""}, {maleCount} male{maleCount !== 1 ? "s" : ""})
                            </Label>
                            <Button
                                type="button"
                                onClick={addKit}
                                variant="outline"
                                className="bg-green-100 dark:bg-green-900/50 text-green-700 dark:text-green-300 hover:bg-green-200 dark:hover:bg-green-800/50"
                            >
                                Add Kit
                            </Button>
                        </div>
                        {kits.length > 0 && (
                            <div className="grid grid-cols-[1fr_1fr_1fr_1fr_1fr_1fr_auto] gap-2 items-center font-medium text-sm text-gray-900 dark:text-gray-100">
                                <span>Kit Number</span>
                                <span>Gender</span>
                                <span>Color</span>
                                <span>Status</span>
                                <span>Birth Weight (kg)</span>
                                <span>Notes</span>
                                <span></span>
                            </div>
                        )}
                        {kits.map((kit, index) => (
                            <div
                                key={kit.kit_number}
                                className="grid grid-cols-[1fr_1fr_1fr_1fr_1fr_1fr_auto] gap-2 items-center"
                            >
                                <div>
                                    <Label htmlFor={`kit_number_${index}`} className="sr-only">
                                        Kit Number
                                    </Label>
                                    <Input
                                        id={`kit_number_${index}`}
                                        value={kit.kit_number}
                                        onChange={(e) => updateKit(index, "kit_number", e.target.value)}
                                        className="text-sm px-2 py-1 h-8 bg-white/50 dark:bg-gray-700/50 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-gray-100"
                                        style={{ width: "80px" }}
                                        required
                                    />
                                </div>
                                <div>
                                    <Label htmlFor={`gender_${index}`} className="sr-only">
                                        Gender
                                    </Label>
                                    <Select
                                        value={kit.gender}
                                        onValueChange={(value) => updateKit(index, "gender", value)}
                                    >
                                        <SelectTrigger className="text-sm px-2 py-1 h-8 bg-white/50 dark:bg-gray-700/50 border-gray-300 dark:border-gray-600">
                                            <SelectValue placeholder="Gender" />
                                        </SelectTrigger>
                                        <SelectContent className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600">
                                            <SelectItem value="male">Male</SelectItem>
                                            <SelectItem value="female">Female</SelectItem>
                                        </SelectContent>
                                    </Select>
                                </div>
                                <div>
                                    <Label htmlFor={`color_${index}`} className="sr-only">
                                        Color
                                    </Label>
                                    <Select
                                        value={kit.color}
                                        onValueChange={(value) => updateKit(index, "color", value)}
                                    >
                                        <SelectTrigger className="text-sm px-2 py-1 h-8 bg-white/50 dark:bg-gray-700/50 border-gray-300 dark:border-gray-600">
                                            <SelectValue placeholder="Color" />
                                        </SelectTrigger>
                                        <SelectContent className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600">
                                            {colors.map((color) => (
                                                <SelectItem key={color} value={color}>
                                                    {color}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </div>
                                <div>
                                    <Label htmlFor={`status_${index}`} className="sr-only">
                                        Status
                                    </Label>
                                    <Select
                                        value={kit.status}
                                        onValueChange={(value) => updateKit(index, "status", value)}
                                    >
                                        <SelectTrigger className="text-sm px-2 py-1 h-8 bg-white/50 dark:bg-gray-700/50 border-gray-300 dark:border-gray-600">
                                            <SelectValue placeholder="Status" />
                                        </SelectTrigger>
                                        <SelectContent className="bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600">
                                            <SelectItem value="alive">Alive</SelectItem>
                                            <SelectItem value="dead">Dead</SelectItem>
                                        </SelectContent>
                                    </Select>
                                </div>
                                <div>
                                    <Label htmlFor={`birth_weight_${index}`} className="sr-only">
                                        Birth Weight
                                    </Label>
                                    <Input
                                        id={`birth_weight_${index}`}
                                        type="number"
                                        step="0.01"
                                        value={kit.birth_weight}
                                        onChange={(e) => updateKit(index, "birth_weight", e.target.value)}
                                        className="text-sm px-2 py-1 h-8 bg-white/50 dark:bg-gray-700/50 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-gray-100"
                                        style={{ width: "60px" }}
                                        required
                                    />
                                </div>
                                <Button
                                    type="button"
                                    variant="ghost"
                                    size="sm"
                                    onClick={() => removeKit(index)}
                                    className="text-red-600 dark:text-red-400 hover:bg-red-100 dark:hover:bg-red-900/30 h-8 w-8 p-0"
                                >
                                    <Trash2 className="h-4 w-4" />
                                </Button>
                            </div>
                        ))}
                        {kits.length === 0 && (
                            <p className="text-gray-600 dark:text-gray-400 text-sm text-center">
                                No kits added. Click "Add Kit" to start.
                            </p>
                        )}
                    </div>
                    <div className="flex justify-end gap-2">
                        <Button
                            type="button"
                            variant="outline"
                            onClick={onClose}
                            className="bg-gray-200 dark:bg-gray-600 text-gray-900 dark:text-gray-100"
                        >
                            Cancel
                        </Button>
                        <Button
                            type="submit"
                            disabled={isLoading || kits.length === 0}
                            className="bg-gradient-to-r from-green-500 to-blue-500 hover:from-green-600 hover:to-blue-600 text-white"
                        >
                            {isLoading ? "Submitting..." : `Add ${kits.length} Kit${kits.length !== 1 ? "s" : ""}`}
                        </Button>
                    </div>
                </form>
            </DialogContent>
        </Dialog>
    );
}