export const breeds = [
    "New Zealand White",
    "Californian",
    "Dutch",
    "Flemish Giant",
    "Mini Rex",
    "Angora",
    "Havana",
    "Lionhead",
    "Silver Fox",
    "Checkered Giant",
    "English Spot",
    "Cinnamon",
    "American",
    "Thrianta",
    "Satin",
];

export const colors = [
    "White",
    "Black",
    "Brown",
    "Gray",
    "Chocolate brown",
    "Golden",
    "Silver",
    "Blue",
    "Rust colored",
    "Orange-red",
    "Ivory",
    "White with black points",
    "Black and white",
    "White with black spots",
    "Black and white spotted",
];

export const planetNames = [
    "Mercury",
    "Venus",
    "Earth",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
    "Pluto",
    "Ceres",
    "Eris",
    "Makemake",
    "Haumea",
    "Sedna",
    "Quaoar",
    "Orcus",
    "Varuna",
    "Ixion",
    "Chaos",
    "Huya",
    "Altjira",
    "Salacia",
    "Varda",
    "Gongong",
];