import type { Rabbit, Hutch, Row } from "./types"

export const mockRows: Row[] = [
  {
    name: "Mercury",
    description: "Primary breeding row with premium hutches",
    capacity: 18,
    occupied: 18,
    createdAt: "2024-01-01T00:00:00Z",
  },
]

export const mockRabbits: Rabbit[] = [
  {
    id: "1",
    rabbit_id: "RB-001",
    name: "RB-001",
    gender: "female",
    breed: "New Zealand White",
    color: "White",
    birthDate: "2023-03-15",
    weight: 4.2,
    hutch_id: "Mercury-A1",
    parentMale: "RB-019",
    parentFemale: "RB-020",
    isPregnant: false,
    lastMatingDate: "2024-01-15",
    matedWith: "RB-004",
    totalLitters: 3,
    totalKits: 18,
    healthRecords: [
      {
        id: "h1",
        type: "Vaccination",
        description: "RHDV2 Vaccination",
        date: "2024-01-10",
        nextDue: "2024-01-08",
        status: "overdue",
        veterinarian: "Dr. Smith",
      },
      {
        id: "h2",
        type: "Health Check",
        description: "Routine health examination",
        date: "2024-01-05",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "150g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "2:00 PM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    rabbit_id: "RB-002",
    name: "RB-002",
    gender: "female",
    breed: "Californian",
    color: "White with black points",
    birthDate: "2023-05-20",
    weight: 3.8,
    hutch_id: "Mercury-B2",
    isPregnant: true,
    lastMatingDate: "2024-01-01",
    matedWith: "RB-005",
    expectedBirthDate: "2024-01-25",
    totalLitters: 2,
    totalKits: 12,
    healthRecords: [
      {
        id: "h3",
        type: "Prenatal Check",
        description: "Pregnancy health check",
        date: "2024-01-15",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "160g",
      feedType: "Pellets + Hay + Vegetables",
      times: ["6:00 AM", "2:00 PM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    rabbit_id: "RB-003",
    name: "RB-003",
    gender: "female",
    breed: "Dutch",
    color: "Black and white",
    birthDate: "2023-07-10",
    weight: 3.5,
    hutch_id: "Mercury-C1",
    isPregnant: false,
    totalLitters: 1,
    totalKits: 6,
    healthRecords: [
      {
        id: "h4",
        type: "Vaccination",
        description: "Annual vaccination",
        date: "2024-01-12",
        nextDue: "2025-01-12",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "140g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "4",
    rabbit_id: "RB-004",
    name: "RB-004",
    gender: "male",
    breed: "New Zealand White",
    color: "White",
    birthDate: "2022-12-05",
    weight: 5.1,
    hutch_id: "Mercury-A3",
    isPregnant: false,
    totalLitters: 0,
    totalKits: 0,
    healthRecords: [
      {
        id: "h5",
        type: "Health Check",
        description: "Routine examination",
        date: "2024-01-10",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "180g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "2:00 PM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "5",
    rabbit_id: "RB-005",
    name: "RB-005",
    gender: "male",
    breed: "Californian",
    color: "White with black points",
    birthDate: "2023-01-15",
    weight: 4.8,
    hutch_id: "Mercury-B4",
    isPregnant: false,
    totalLitters: 0,
    totalKits: 0,
    healthRecords: [
      {
        id: "h6",
        type: "Vaccination",
        description: "RHDV2 Vaccination",
        date: "2024-01-08",
        nextDue: "2025-01-08",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "170g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "2:00 PM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "6",
    rabbit_id: "RB-006",
    name: "RB-006",
    gender: "male",
    breed: "Dutch",
    color: "Brown and white",
    birthDate: "2023-04-20",
    weight: 4.3,
    hutch_id: "Mercury-C3",
    isPregnant: false,
    totalLitters: 0,
    totalKits: 0,
    healthRecords: [
      {
        id: "h7",
        type: "Health Check",
        description: "Routine examination",
        date: "2024-01-05",
        nextDue: "2024-01-22",
        status: "pending",
      },
    ],
    feedingSchedule: {
      dailyAmount: "165g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "6:00 PM"],
      lastFed: "2024-01-19T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "7",
    rabbit_id: "RB-007",
    name: "RB-007",
    gender: "female",
    breed: "Flemish Giant",
    color: "Gray",
    birthDate: "2023-02-28",
    weight: 6.2,
    hutch_id: "Mercury-A2",
    isPregnant: false,
    totalLitters: 2,
    totalKits: 14,
    healthRecords: [
      {
        id: "h8",
        type: "Vaccination",
        description: "Annual vaccination",
        date: "2024-01-15",
        nextDue: "2025-01-15",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "200g",
      feedType: "Pellets + Hay + Vegetables",
      times: ["6:00 AM", "2:00 PM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "8",
    rabbit_id: "RB-008",
    name: "RB-008",
    gender: "female",
    breed: "Mini Rex",
    color: "Black",
    birthDate: "2023-06-12",
    weight: 2.8,
    hutch_id: "Mercury-B1",
    isPregnant: false,
    totalLitters: 1,
    totalKits: 4,
    healthRecords: [
      {
        id: "h9",
        type: "Health Check",
        description: "Routine examination",
        date: "2024-01-08",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "120g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "9",
    rabbit_id: "RB-009",
    name: "RB-009",
    gender: "female",
    breed: "Angora",
    color: "White",
    birthDate: "2023-08-05",
    weight: 3.2,
    hutch_id: "Mercury-C2",
    isPregnant: false,
    totalLitters: 0,
    totalKits: 0,
    healthRecords: [
      {
        id: "h10",
        type: "Grooming",
        description: "Fur trimming and health check",
        date: "2024-01-10",
        nextDue: "2024-01-24",
        status: "pending",
      },
    ],
    feedingSchedule: {
      dailyAmount: "130g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "2:00 PM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "10",
    rabbit_id: "RB-010",
    name: "RB-010",
    gender: "female",
    breed: "Havana",
    color: "Chocolate brown",
    birthDate: "2023-09-18",
    weight: 3.6,
    hutch_id: "Mercury-A4",
    isPregnant: false,
    totalLitters: 0,
    totalKits: 0,
    healthRecords: [
      {
        id: "h11",
        type: "Vaccination",
        description: "First vaccination",
        date: "2024-01-12",
        nextDue: "2025-01-12",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "145g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "11",
    rabbit_id: "RB-011",
    name: "RB-011",
    gender: "female",
    breed: "Lionhead",
    color: "Golden",
    birthDate: "2023-10-22",
    weight: 2.9,
    hutch_id: "Mercury-B3",
    isPregnant: false,
    totalLitters: 0,
    totalKits: 0,
    healthRecords: [
      {
        id: "h12",
        type: "Health Check",
        description: "Young rabbit health assessment",
        date: "2024-01-05",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "125g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "2:00 PM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "12",
    rabbit_id: "RB-012",
    name: "RB-012",
    gender: "female",
    breed: "Silver Fox",
    color: "Silver",
    birthDate: "2023-11-30",
    weight: 4.1,
    hutch_id: "Mercury-C4",
    isPregnant: false,
    totalLitters: 0,
    totalKits: 0,
    healthRecords: [
      {
        id: "h13",
        type: "Vaccination",
        description: "Initial vaccination series",
        date: "2024-01-18",
        nextDue: "2025-01-18",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "155g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "13",
    rabbit_id: "RB-013",
    name: "RB-013",
    gender: "female",
    breed: "Checkered Giant",
    color: "Black and white spotted",
    birthDate: "2023-01-08",
    weight: 5.8,
    hutch_id: "Mercury-A5",
    isPregnant: false,
    totalLitters: 3,
    totalKits: 21,
    healthRecords: [
      {
        id: "h14",
        type: "Health Check",
        description: "Breeding doe examination",
        date: "2024-01-14",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "190g",
      feedType: "Pellets + Hay + Vegetables",
      times: ["6:00 AM", "2:00 PM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "14",
    rabbit_id: "RB-014",
    name: "RB-014",
    gender: "female",
    breed: "English Spot",
    color: "White with black spots",
    birthDate: "2023-03-25",
    weight: 3.4,
    hutch_id: "Mercury-B5",
    isPregnant: false,
    totalLitters: 1,
    totalKits: 7,
    healthRecords: [
      {
        id: "h15",
        type: "Vaccination",
        description: "Annual booster",
        date: "2024-01-16",
        nextDue: "2025-01-16",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "135g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "15",
    rabbit_id: "RB-015",
    name: "RB-015",
    gender: "female",
    breed: "Cinnamon",
    color: "Rust colored",
    birthDate: "2023-04-14",
    weight: 4.0,
    hutch_id: "Mercury-C5",
    isPregnant: false,
    totalLitters: 2,
    totalKits: 11,
    healthRecords: [
      {
        id: "h16",
        type: "Health Check",
        description: "Post-weaning examination",
        date: "2024-01-11",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "150g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "2:00 PM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "16",
    rabbit_id: "RB-016",
    name: "RB-016",
    gender: "female",
    breed: "American",
    color: "Blue",
    birthDate: "2023-05-03",
    weight: 4.5,
    hutch_id: "Mercury-A6",
    isPregnant: false,
    totalLitters: 1,
    totalKits: 8,
    healthRecords: [
      {
        id: "h17",
        type: "Vaccination",
        description: "Routine vaccination",
        date: "2024-01-13",
        nextDue: "2025-01-13",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "160g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "17",
    rabbit_id: "RB-017",
    name: "RB-017",
    gender: "female",
    breed: "Thrianta",
    color: "Orange-red",
    birthDate: "2023-06-28",
    weight: 3.7,
    hutch_id: "Mercury-B6",
    isPregnant: false,
    totalLitters: 0,
    totalKits: 0,
    healthRecords: [
      {
        id: "h18",
        type: "Health Check",
        description: "First breeding readiness check",
        date: "2024-01-17",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "145g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "2:00 PM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "18",
    rabbit_id: "RB-018",
    name: "RB-018",
    gender: "female",
    breed: "Satin",
    color: "Ivory",
    birthDate: "2023-07-16",
    weight: 3.9,
    hutch_id: "Mercury-C6",
    isPregnant: false,
    totalLitters: 0,
    totalKits: 0,
    healthRecords: [
      {
        id: "h19",
        type: "Vaccination",
        description: "Initial vaccination",
        date: "2024-01-19",
        nextDue: "2025-01-19",
        status: "completed",
      },
    ],
    feedingSchedule: {
      dailyAmount: "148g",
      feedType: "Pellets + Hay",
      times: ["6:00 AM", "6:00 PM"],
      lastFed: "2024-01-20T18:00:00Z",
    },
    createdAt: "2024-01-01T00:00:00Z",
  },
]

export const mockHutches: Hutch[] = [
  // Mercury Row - Level A (Top)
  {
    id: "Mercury-A1",
    rowName: "Mercury",
    level: "A",
    position: 1,
    size: "medium",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-A2",
    rowName: "Mercury",
    level: "A",
    position: 2,
    size: "large",
    material: "wire",
    features: ["water bottle", "feeder", "nesting box"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-A3",
    rowName: "Mercury",
    level: "A",
    position: 3,
    size: "medium",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-A4",
    rowName: "Mercury",
    level: "A",
    position: 4,
    size: "medium",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-A5",
    rowName: "Mercury",
    level: "A",
    position: 5,
    size: "large",
    material: "wire",
    features: ["water bottle", "feeder", "nesting box"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-A6",
    rowName: "Mercury",
    level: "A",
    position: 6,
    size: "medium",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },

  // Mercury Row - Level B (Middle)
  {
    id: "Mercury-B1",
    rowName: "Mercury",
    level: "B",
    position: 1,
    size: "small",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-B2",
    rowName: "Mercury",
    level: "B",
    position: 2,
    size: "medium",
    material: "wire",
    features: ["water bottle", "feeder", "nesting box"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-B3",
    rowName: "Mercury",
    level: "B",
    position: 3,
    size: "small",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-B4",
    rowName: "Mercury",
    level: "B",
    position: 4,
    size: "medium",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-B5",
    rowName: "Mercury",
    level: "B",
    position: 5,
    size: "medium",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-B6",
    rowName: "Mercury",
    level: "B",
    position: 6,
    size: "medium",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },

  // Mercury Row - Level C (Bottom)
  {
    id: "Mercury-C1",
    rowName: "Mercury",
    level: "C",
    position: 1,
    size: "medium",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-C2",
    rowName: "Mercury",
    level: "C",
    position: 2,
    size: "small",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-C3",
    rowName: "Mercury",
    level: "C",
    position: 3,
    size: "medium",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-C4",
    rowName: "Mercury",
    level: "C",
    position: 4,
    size: "medium",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-C5",
    rowName: "Mercury",
    level: "C",
    position: 5,
    size: "medium",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "Mercury-C6",
    rowName: "Mercury",
    level: "C",
    position: 6,
    size: "medium",
    material: "wire",
    features: ["water bottle", "feeder"],
    isOccupied: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
]
